### ISSUE TITLE
Message receiver/sender can be constructing using the same connection object (not connection string).

### ISSUE THREAD

**Issue by alrod** [Azure/azure-functions-servicebus-extension#123]
https://github.com/Azure/azure-functions-servicebus-extension/issues/120#issuecomment-730653919

**Comment by sidkri** [comment]
Based on the discussion on the issue, the goal here is to re-use connections to Service Bus across MessageReceivers and MessageSenders.  We can start caching ServiceBusConnection objects keyed on the connection string and use this object when creating MessageReceiver and MessageSender objects instead of the connection string.  @alrod do you feel we should continue caching the MessageReceiver and MessageSender as well in this case?

**Comment by jsheetzati** [comment]
Any traction on this issue? We are starting to see issues as we add more ServiceBusTriggers to our Azure Function project.

**Comment by alrod** [comment]
is this  can be refactored in track2?

**Comment by alrod** [comment]
done in https://www.nuget.org/packages/Microsoft.Azure.WebJobs.Extensions.ServiceBus/5.3.0
