### ISSUE TITLE
Unable to set ServiceBus connectivity Mode to HTTPS for development

### ISSUE THREAD

**Issue by invisibleaxm** [Azure/azure-functions-servicebus-extension#36]
#### Investigative information

Please provide the following:

- Timestamp: All the time
- Function App version (1.0 or 2.0):

Both 1.0 or 2.0

- Function App name: Any 

#### Repro steps

Provide the steps required to reproduce the problem:

Create a new function app with a ServiceBus Topic trigger (I'm sure its the same for queue trigger but i have not tried it) and try to connect behind a firewall that blocks non https outbound ports and compile and run the local app.

#### Expected behavior

Ideally, we would be able to specify the protocol (i.e. https) for outbound binding, that way we can develop behind a firewalled environment and still connect to ServiceBus (fwis, i have other console apps where I simply specify erviceBusEnvironment.SystemConnectivity.Mode = ConnectivityMode.Https; and I am able to connect )

#### Actual behavior

I am not able to change the default connectivity mode and as a result, every time I do development I end up a connection reset error:

 Microsoft.Azure.ServiceBus: An existing connection was forcibly closed by the remote host ErrorCode: ConnectionReset. Microsoft.Azure.Amqp: An existing connection was forcibly closed by the remote host.

#### Known workarounds

Turn off firewall that blocks outbound ports.

#### Related information 

Provide any related information 

* C#
* Links to source : default scafold from new solution/function.
* Bindings used: ServiceBus trigger

**Comment by brettsam** [comment]
@alrod -- even though there appears to be a workaround, we may want to explicitly expose this in the SB options.

**Comment by gastonmuijtjens** [comment]
@alrod @brettsam Any update on this? Is there any way to specify the transport type `AmqpWebSockets` **without** using a connection strings? Since version 5.0.0 (now stable) [Managed Identity authentication is supported](https://docs.microsoft.com/en-us/dotnet/api/overview/azure/microsoft.azure.webjobs.extensions.servicebus-readme-pre#managed-identity-authentication). Because of security policies enforced by our organization we only are allowed to use Managed Identity authentication and connection strings are not an option for us. We have to use `AmqpWebSockets` in development due to firewall policies in our organization.

**Comment by gastonmuijtjens** [comment]
I found another workaround, you can add this line to your `local.settings.json` in your Function App:

```json
{
   "AzureWebJobs:extensions:ServiceBus:TransportType: "1"
}
```

The Service Bus Azure Functions extensions will automatically pick up this setting and use `AmqpWebSockets` as the transport type. No need for a connection string.

**Comment by YevhenSemikon** [comment]
After update of Microsoft.Azure.WebJobs.Extensions.ServiceBus from from 4.1.0 to  5.1.0 or 5.2.0, the workaround with connection string is not working anymore.  is there any other ways to achieve it?
