### ISSUE TITLE
Same message triggers execution second time

### ISSUE THREAD

**Issue by DennisInSky** [Azure/azure-functions-servicebus-extension#87]
Hi guys,

We ran into a situation when a Web Job service bus trigger got executed twice for the same message without any obvious reason. Our set-up is:
1. The trigger is configured to use sessions
2. Lock duration on service bus queue server is 5 minutes
3. ServiceBusOptions is configured as
```
"ServiceBus": {
    "PrefetchCount": 1,
    "SessionHandlerOptions": {
        "MaxAutoRenewDuration": "00:05:00"
    }
}
```
4. First message is processed for 4 minutes, i.e. less then lock time
Details are available on the attached screenshot. Message ID is "80b6b9be99f34783b35294f54c8cdd1b".

There are no any log messages from service bus at all. The only messages appear after it fails to complete the first message and receive the next one with the SessionLockLostException exception (available on the second screenshot) which is obviously because it had acquired session lock for the second invocation.

We use "Microsoft.Azure.WebJobs.Extensions.ServiceBus" Version="4.1.1".

Do you have any ideas why it can be so or how we can investigated the cause of it further?

<img width="962" alt="Same Message Invocation" src="https://user-images.githubusercontent.com/6682974/83199663-94360f00-a139-11ea-911a-934c98fdf661.png">

<img width="960" alt="ServiceBusErrors" src="https://user-images.githubusercontent.com/6682974/83200056-5d142d80-a13a-11ea-8791-0231eb3198f1.png">

**Comment by sidkri** [comment]
Hi @DennisInSky,
After investigating a similar issue and discussing with the Service Bus team, I learned that this can happen if there is a Service Bus backend host upgrade/migration since session lock information is maintained at the backend host level and other hosts (e.g. backup host) do not share this state.  The team is investigating options to replicate such state across all relevant hosts to avoid such issues.  In the example you provided, its likely that the backend host handling that session changed between the first dispatch of the message and the second which is why the new host allowed the another functions host to secure the lock on that session as it is unaware of the session being locked.

If processing of a message is not idempotent in your scenario, one way to mitigate against duplicate processing could be to set “AutoComplete” to false in "serviceBus" settings in host.json and manage the message lock lifecycle in your code (you can add a "MessageReceiver" parameter to your function to manage completion). This will allow you make your logic transactional and prevent duplicate message processing (e.g. roll back changes if service bus message completion fails).
